spring.application.name=api-and-jasper-using-spring-boot-security
logging.level.root[0]=warn
logging.level.root[1]=debug
spring.main.banner-mode=off
spring.config.import=classpath:info/database.properties
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=${MYSQL_DRIVER}
spring.jpa.show-sql=true
